apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-api
  template:
    metadata:
      labels:
        app: survey-api
    spec:
      containers:
        - name: survey-api
          image: ghcr.io/dhaval3890/survey-quality-tool:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: survey-api-service
spec:
  selector:
    app: survey-api
  type: NodePort
  ports:
    - port: 8000        # service port inside cluster
      targetPort: 8000  # container port
      nodePort: 30110   # port on your laptop (Docker Desktop)
